### PR TITLE
Adding a file for Sharon, MA

### LINKED ISSUE #277: Add an test issue
Test

### PR DESCRIPTION
**Pull request by fangy4**
This pull request resolves #277

### CODE REVIEW

**Comment by leefp** [comment]
hey....you're from Sharon? I grew up there....
What side of time, do you live in?

**Comment by fangy4** [comment]
@leefp Hello fellow Sharonite, I live in Sharon Woods.

**Comment by leefp** [comment]
Too funny. That's exactly where I lived too! I was on Matross lane. What about you?

**Comment by fangy4** [comment]
Reeve Rd. Very close.

**Comment by leefp** [comment]
Yup...very close. I went to grade school with a girl on that street.

**Comment by fangy4** [comment]
Not sure if the family still lives in that street. Lots have been changed.

**Pull request merged**
