### PR TITLE
Ashj1 adding file for Hudson, MA

### LINKED ISSUE #13: Add a file for ashj1 hometown
# Adding file for Hudson, Ma

- [x] create branch?
- [x] Add file
- [x] Commit changes
- [x] Pull Request
- [x] code review :roll_eyes: 
- [ ] Approval
- [ ] merge

### PR DESCRIPTION
**Pull request by ashj1**
this resolves #13

### CODE REVIEW

**Comment by ashj1** [comment]
@githubteacher it looks like my file is binary?

**Comment by jschuler** [comment]
Nice, I am also from Hudson :)

**Comment by mhamel12** [comment]
LGTM

**Comment by leefp** [comment]
I don't want any files from GEU #3

**Pull request merged**
